name: Build and Deploy to GitHub Pages

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight (UTC)
  push:
    branches:
      - main  # Replace 'main' with your default branch if different

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Jinja2

    - name: Run generate_static.py
      run: |
        python generate_static.py

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # The directory containing your index.html file
