name: Build and Deploy to GitHub Pages

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight (UTC)
  push:
    branches:
      - main  # Replace 'main' with your default branch if different

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Jinja2
        pip install Flask
        pip install requests

    - name: Run generate_static.py
      run: |
        python generate_static.py

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v2.0.0
    
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v2.0.3

